# RedHat specific package installations
- include: RedHat.yml
  when: ansible_os_family  == "RedHat"

# Debian specific package installations
- include: Debian.yml
  when: ansible_os_family  == "Debian"

# Gentoo specific package installations
- include: Gentoo.yml
  when: ansible_os_family  == "Gentoo"
